before:
  hooks:
    - go mod tidy

builds:
  - main: cmd/cli/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6  # Raspberry Pi A, B, Zero
      - 7  # Raspberry Pi 2, 3, 4

archives:
  - files:
      - none*
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - package_name: pg2s3
    homepage: https://github.com/theandrew168/pg2s3
    maintainer: Andrew Dailey <andrew@shallowbrooksoftware.com>
    description: Simple PostgreSQL backups to S3-compatible storage
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: script/pg2s3.service
        dst: /lib/systemd/system/pg2s3.service
        type: config
      - src: script/pg2s3.conf
        dst: /etc/pg2s3.conf
        type: config
    scripts:
      postinstall: script/postinstall.sh
      preremove: script/preremove.sh
      postremove: script/postremove.sh

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
