before:
  hooks:
    - go mod tidy

builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - package_name: pg2s3
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/theandrew168/pg2s3
    maintainer: Andrew Dailey <andrew@shallowbrooksoftware.com>
    description: Simple PostgreSQL backups to S3-compatible storage
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: script/pg2s3.service
        dst: /lib/systemd/system/pg2s3.service
        type: config
      - src: script/pg2s3.conf
        dst: /etc/pg2s3.conf
        type: config
    scripts:
      postinstall: script/postinstall.sh
      preremove: script/preremove.sh
      postremove: script/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
