name: Test

on: [push, pull_request]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install latest postgres client tools
      run: |
        sudo apt install -y postgresql-client-16
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Start containers
      run: |
        docker-compose up -d
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Run tests
      run: |
        go test ./...
