name: Test

on: [push, pull_request]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Start containers
      run: |
        docker-compose up -d
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run tests
      run: |
        go test ./...
      env:
        PG2S3_PG_CONNECTION_URI: 'postgresql://postgres:postgres@localhost:5432/postgres'
        PG2S3_S3_ENDPOINT: 'localhost:9000'
        PG2S3_S3_ACCESS_KEY_ID: 'AKIAIOSFODNN7EXAMPLE'
        PG2S3_S3_SECRET_ACCESS_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
        PG2S3_S3_BUCKET_NAME: 'pg2s3'
        PG2S3_BACKUP_PREFIX: 'pg2s3'
        PG2S3_BACKUP_RETENTION: 30
