name: Test

on: [push, pull_request]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      minio:
        image: bitnami/minio
        env:
          MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
          MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run tests
      run: |
        go test ./...
      env:
        PG2S3_PG_CONNECTION_URI: 'postgresql://postgres:postgres@localhost:5432/postgres'
        PG2S3_S3_ENDPOINT: 'localhost:9000'
        PG2S3_S3_ACCESS_KEY_ID: 'AKIAIOSFODNN7EXAMPLE'
        PG2S3_S3_SECRET_ACCESS_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
        PG2S3_BUCKET_NAME: 'pg2s3'
        PG2S3_BACKUP_PREFIX: 'pg2s3'
