name: Test

on: [push, pull_request]

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
    # Based on:
    # https://www.postgresql.org/download/linux/ubuntu/
    - name: Install latest PostgreSQL client tools
      run: |
        sudo apt install -y postgresql-common
        sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
        sudo apt purge -y postgresql-client-common
        sudo apt install -y postgresql-client
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Start containers
      run: |
        docker-compose up -d
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    - name: Run tests
      run: |
        go test ./...
